// generated by tools/schema_codegen.py (OpenWrite), do not edit
// sources:
//   review-v2-decision.schema.json sha256:a7c5214a498a $id: https://openwrite.dev/schemas/review-v2-decision.schema.json
//   review-manifest-v2.schema.json sha256:c74873990a9d $id: https://openwrite.dev/schemas/review-manifest-v2.schema.json
//   delivery-manifest-v2.schema.json sha256:cb149eae6952 $id: https://openwrite.dev/schemas/delivery-manifest-v2.schema.json
//   delivery-stage-v2.schema.json sha256:04d2637e1e4d $id: https://openwrite.dev/schemas/delivery-stage-v2.schema.json
//   model-benchmark-v1.schema.json sha256:4d56ab63c3ea $id: https://openwrite.dev/schemas/model-benchmark-v1.schema.json
//   model-profile-surface-v1.schema.json sha256:d44a07240d23 $id: https://openwrite.dev/schemas/model-profile-surface-v1.schema.json
//   task-surface-v1.schema.json sha256:b25a2195014a $id: https://openwrite.dev/schemas/task-surface-v1.schema.json
//   research-surface-v1.schema.json sha256:c66c3f1494a1 $id: https://openwrite.dev/schemas/research-surface-v1.schema.json
//   model-connection-test-v1.schema.json sha256:60824b0b20f4 $id: https://openwrite.dev/schemas/model-connection-test-v1.schema.json
/** OpenWrite review v2 decision. Extra keys are allowed (additionalProperties). */
export interface ReviewV2Decision {
  schema_version: "openwrite.review.v2"
  execution_status: "completed" | "partial" | "failed"
  quality_score: number | null
  coverage: number
  gate_status: "pass" | "blocked" | "inconclusive"
  delivery_status: "pass" | "revise" | "blocked" | "inconclusive" | "stale"
  production_gate_status: "pass" | "revise" | "blocked" | "inconclusive" | "stale" | "disabled" | "disabled_uncalibrated"
  [key: string]: unknown
}

/** dsh-novel review manifest v2. Extra keys are allowed (additionalProperties). */
export interface ReviewManifestV2 {
  schemaVersion: "dsh-novel.review.manifest.v2"
  recordType: "review"
  chapterId: string
  verdict: "pass" | "fail" | "inconclusive"
  decisionSource?: "v2" | "v1-adapter"
  threshold?: number
  coverage?: number
  qualityScore?: number | null
  [key: string]: unknown
}

/** DeliveryManifestV2Stage. Extra keys are allowed (additionalProperties). */
export interface DeliveryManifestV2Stage {
  schemaVersion: "dsh-novel.delivery.stage.v2"
  recordType: "delivery-stage"
  chapterId: string
  stage: string
  verdict: "pass" | "fail" | "inconclusive"
  status: string
  evidence: Record<string, unknown>
  [key: string]: unknown
}

/** dsh-novel delivery manifest v2. Extra keys are allowed (additionalProperties). */
export interface DeliveryManifestV2 {
  schemaVersion: "dsh-novel.delivery.manifest.v2"
  recordType: "chapter-delivery"
  chapterId: string
  novelId?: string
  threshold?: number
  decisionSource?: "v2" | "v1-adapter"
  readyForDelivery?: boolean
  stages: Record<string, DeliveryManifestV2Stage>
  [key: string]: unknown
}

/** dsh-novel delivery stage v2. Extra keys are allowed (additionalProperties). */
export interface DeliveryStageV2 {
  schemaVersion: "dsh-novel.delivery.stage.v2"
  recordType: "delivery-stage"
  chapterId: string
  stage: string
  verdict: "pass" | "fail" | "inconclusive"
  status: string
  evidence: Record<string, unknown>
  [key: string]: unknown
}

/** ModelBenchmarkV1CandidateUsage. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1CandidateUsage {
  prompt_tokens?: number | null
  completion_tokens?: number | null
  reasoning_tokens?: number | null
  total_tokens?: number | null
  [key: string]: unknown
}

/** ModelBenchmarkV1CandidateError. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1CandidateError {
  code: string
  message: string
  [key: string]: unknown
}

/** ModelBenchmarkV1Candidate. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1Candidate {
  candidate_id: string
  writer_profile: Record<string, unknown>
  reliability_status: "completed" | "failed"
  usage?: ModelBenchmarkV1CandidateUsage | null
  cost_usd?: number | null
  cost_reported?: boolean
  latency_ms?: number | null
  error?: ModelBenchmarkV1CandidateError | null
  [key: string]: unknown
}

/** ModelBenchmarkV1EvaluationUsage. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1EvaluationUsage {
  prompt_tokens?: number | null
  completion_tokens?: number | null
  reasoning_tokens?: number | null
  total_tokens?: number | null
  [key: string]: unknown
}

/** ModelBenchmarkV1EvaluationError. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1EvaluationError {
  code: string
  message: string
  [key: string]: unknown
}

/** ModelBenchmarkV1Evaluation. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1Evaluation {
  candidate_id: string
  reviewer_profile: Record<string, unknown>
  execution_status: "completed" | "partial" | "failed"
  usage?: ModelBenchmarkV1EvaluationUsage | null
  cost_usd?: number | null
  cost_reported?: boolean
  latency_ms?: number | null
  error?: ModelBenchmarkV1EvaluationError | null
  [key: string]: unknown
}

/** ModelBenchmarkV1Config. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1Config {
  writer_profile_ids: string[]
  reviewer_profile_ids: string[]
  repeats?: number
  target_words?: number
  concurrency?: number
  blind_review?: boolean
  run_scoped_profiles?: boolean
  execution_mode?: "framework" | "creative"
  [key: string]: unknown
}

/** ModelBenchmarkV1Summary. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1Summary {
  latency_ms_total?: number | null
  failed_candidates?: number
  [key: string]: unknown
}

/** OpenWrite model benchmark v1 artifact. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1 {
  schema_version: "openwrite.model-benchmark.v1"
  run_id: string
  status: "completed" | "partial" | "failed"
  context_hash: string
  task_id?: string
  started_at?: string
  candidates: ModelBenchmarkV1Candidate[]
  evaluations: ModelBenchmarkV1Evaluation[]
  config: ModelBenchmarkV1Config
  summary?: ModelBenchmarkV1Summary
  [key: string]: unknown
}

/** OpenWrite independent chat and embedding model surface v1. Extra keys are allowed (additionalProperties). */
export interface ModelProfileSurfaceV1 {
  schema_version: "openwrite.model-profile.v1"
  default_profile_id: string
  active_embedding_profile_id: string
  profiles: unknown[]
  embedding_profiles: unknown[]
  routes: Record<string, string>
  [key: string]: unknown
}

/** TaskSurfaceV1TaskProgress. Extra keys are allowed (additionalProperties). */
export interface TaskSurfaceV1TaskProgress {
  completed_units: number
  total_units: number
  ratio: number | null
  unit_kind: "candidates" | "evaluations" | "chapters" | "files"
  [key: string]: unknown
}

/** TaskSurfaceV1TaskError. Extra keys are allowed (additionalProperties). */
export interface TaskSurfaceV1TaskError {
  code: string
  message: string
  recoverable: boolean
  failed_stage?: string | null
  [key: string]: unknown
}

/** TaskSurfaceV1TaskResultRef. Extra keys are allowed (additionalProperties). */
export interface TaskSurfaceV1TaskResultRef {
  type: "chapter" | "review" | "revision" | "research_report" | "benchmark_run" | "import" | "archive"
  id: string
  [key: string]: unknown
}

/** TaskSurfaceV1Task. Extra keys are allowed (additionalProperties). */
export interface TaskSurfaceV1Task {
  task_id: string
  type: string
  status: "pending" | "running" | "awaiting_confirmation" | "completed" | "failed" | "cancelled" | "interrupted"
  phase: "queued" | "reading" | "preparing" | "model" | "validating" | "committing" | "complete" | null
  phase_index: number | null
  progress: TaskSurfaceV1TaskProgress | null
  attempt: number
  retryable: boolean
  created_at: string | null
  updated_at: string | null
  started_at: string | null
  completed_at: string | null
  error: TaskSurfaceV1TaskError | null
  result_ref: TaskSurfaceV1TaskResultRef | null
  input_summary: string | null
  chapter_id: string | null
  schema_version: string
  [key: string]: unknown
}

/** OpenWrite task surface v1 (credential-free). Extra keys are allowed (additionalProperties). */
export interface TaskSurfaceV1 {
  schema_version: "openwrite.task-surface.v1"
  phase_order: "queued" | "reading" | "preparing" | "model" | "validating" | "committing" | "complete"[]
  tasks: TaskSurfaceV1Task[]
  counts: Record<string, unknown>
  [key: string]: unknown
}

/** ResearchSurfaceV1SettingsSearchProvider. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1SettingsSearchProvider {
  id: "bocha" | "bing" | "jina" | "none"
  label: string
  requires_api_key: boolean
  configured: boolean
  credential_configured: boolean
  [key: string]: unknown
}

/** ResearchSurfaceV1Settings. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1Settings {
  search_provider: "bocha" | "bing" | "jina" | "none"
  search_providers: ResearchSurfaceV1SettingsSearchProvider[]
  [key: string]: unknown
}

/** ResearchSurfaceV1ReportModelProfile. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1ReportModelProfile {
  id: string | null
  label: string | null
  model: string | null
  provider: string | null
  [key: string]: unknown
}

/** ResearchSurfaceV1ReportSource. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1ReportSource {
  title: string
  url: string
  source_type: string
  cited: boolean
  [key: string]: unknown
}

/** ResearchSurfaceV1ReportUsage. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1ReportUsage {
  total_tokens: number | null
  reported: boolean
  [key: string]: unknown
}

/** ResearchSurfaceV1ReportCostUsd. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1ReportCostUsd {
  value: number | null
  reported: boolean
  [key: string]: unknown
}

/** ResearchSurfaceV1ReportFailure. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1ReportFailure {
  code: string
  message: string
  [key: string]: unknown
}

/** ResearchSurfaceV1Report. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1Report {
  id: string
  title: string
  status: "succeeded" | "failed" | "needs_human_review" | "unknown"
  episode_id: string | null
  task_id: string | null
  created_at: string | null
  completed_at: string | null
  model_profile: ResearchSurfaceV1ReportModelProfile | null
  search_provider: string | null
  sources: ResearchSurfaceV1ReportSource[] | null
  sources_status: "ok" | "unavailable"
  source_count: number | null
  word_count: number | null
  latency_ms: number | null
  usage: ResearchSurfaceV1ReportUsage
  cost_usd: ResearchSurfaceV1ReportCostUsd
  failure: ResearchSurfaceV1ReportFailure | null
  metrics: Record<string, unknown>
  path: string
  bytes: number
  [key: string]: unknown
}

/** ResearchSurfaceV1ModelRoute. Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1ModelRoute {
  profile_id: string
  label: string
  model: string
  provider: string
  configured: boolean
  compatible: boolean
  [key: string]: unknown
}

/** OpenWrite research surface v1 (credential-free). Extra keys are allowed (additionalProperties). */
export interface ResearchSurfaceV1 {
  schema_version: "openwrite.research-surface.v1"
  available: boolean
  node_ready: boolean
  pnpm_ready: boolean
  package_ready: boolean
  dependencies_ready: boolean
  setup_hint: string
  settings: ResearchSurfaceV1Settings
  reports: ResearchSurfaceV1Report[]
  model_route: ResearchSurfaceV1ModelRoute
  [key: string]: unknown
}

/** OpenWrite model connection test v1 success payload (chat and embedding variants). Extra keys are allowed (additionalProperties). */
export interface ModelConnectionTestV1 {
  ok: true
  status: "ok"
  provider: string
  model: string
  latency_ms: number
  tested_at: string
  reply?: string
  provider_label?: string
  dimension?: number
  max_tokens?: number
  base_url?: string
  vectors?: number
  [key: string]: unknown
}

type SchemaMap = Record<string, unknown>

function typeOk(value: unknown, name: string): boolean {
  switch (name) {
    case 'object': return value !== null && typeof value === 'object' && !Array.isArray(value)
    case 'array': return Array.isArray(value)
    case 'null': return value === null
    case 'integer': return Number.isInteger(value)
    case 'number': return typeof value === 'number' && !Number.isNaN(value)
    default: return typeof value === name
  }
}

/** Minimal JSON Schema subset validator mirroring OpenWrite
 * `tools/schema_lint.py` and `scripts/schema-lint.mjs`. */
export function validateSchema(value: unknown, schema: SchemaMap, path = '$', root: SchemaMap = schema): string[] {
  const errors: string[] = []
  const fail = (message: string) => errors.push(`${path}: ${message}`)

  const ref = schema['$ref']
  if (typeof ref === 'string' && ref.startsWith('#/')) {
    let resolved: unknown = root
    for (const part of ref.slice(2).split('/')) resolved = (resolved as SchemaMap)?.[part]
    if (resolved && typeof resolved === 'object') return validateSchema(value, resolved as SchemaMap, path, root)
  }

  const rawType = schema['type']
  if (rawType !== undefined) {
    const names = Array.isArray(rawType) ? rawType.map(String) : [String(rawType)]
    if (!names.some(name => typeOk(value, name))) {
      const got = value === null ? 'null' : Array.isArray(value) ? 'array' : typeof value
      fail(`expected type ${names.join('/')}, got ${got}`)
      return errors
    }
  }

  if (schema['const'] !== undefined && value !== schema['const']) {
    fail(`expected const ${JSON.stringify(schema['const'])}, got ${JSON.stringify(value)}`)
  }

  const enumValues = schema['enum']
  if (Array.isArray(enumValues) && !enumValues.includes(value)) {
    fail(`${JSON.stringify(value)} not in enum ${JSON.stringify(enumValues)}`)
  }

  if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
    const record = value as Record<string, unknown>
    for (const key of (schema['required'] as string[] | undefined) ?? []) {
      if (!(key in record)) fail(`missing required property '${key}'`)
    }
    for (const key of (schema['disallowed'] as string[] | undefined) ?? []) {
      if (key in record) fail(`forbidden credential-like property '${key}' must not appear`)
    }
    const properties = (schema['properties'] as Record<string, SchemaMap> | undefined) ?? {}
    const additional = schema['additionalProperties']
    for (const [key, sub] of Object.entries(record)) {
      if (key in properties) {
        errors.push(...validateSchema(sub, properties[key] as SchemaMap, `${path}.${key}`, root))
      } else if (additional === false) {
        fail(`unexpected property '${key}'`)
      } else if (additional !== undefined && typeof additional === 'object') {
        errors.push(...validateSchema(sub, additional as SchemaMap, `${path}.${key}`, root))
      }
    }
    const minProperties = schema['minProperties']
    if (typeof minProperties === 'number' && Object.keys(record).length < minProperties) {
      fail(`expected at least ${minProperties} properties, got ${Object.keys(record).length}`)
    }
  }

  const items = schema['items']
  if (Array.isArray(value) && items !== undefined && typeof items === 'object') {
    value.forEach((item, index) => {
      errors.push(...validateSchema(item, items as SchemaMap, `${path}[${index}]`, root))
    })
  }

  if (typeof value === 'number' && !Number.isNaN(value)) {
    const minimum = schema['minimum']
    if (typeof minimum === 'number' && value < minimum) {
      fail(`${value} is less than minimum ${minimum}`)
    }
    const maximum = schema['maximum']
    if (typeof maximum === 'number' && value > maximum) {
      fail(`${value} is greater than maximum ${maximum}`)
    }
  }

  if (typeof value === 'string') {
    const minLength = schema['minLength']
    if (typeof minLength === 'number' && value.length < minLength) {
      fail(`string shorter than minLength ${minLength}`)
    }
    const pattern = schema['pattern']
    if (typeof pattern === 'string' && new RegExp(pattern).test(value) === false) {
      fail(`'${value}' does not match pattern '${pattern}'`)
    }
  }

  return errors
}

const SCHEMAS: Record<string, SchemaMap> = {
  "delivery_manifest_v2": {
    "$id": "https://openwrite.dev/schemas/delivery-manifest-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "decisionSource": {
        "enum": [
          "v2",
          "v1-adapter"
        ]
      },
      "novelId": {
        "minLength": 1,
        "type": "string"
      },
      "readyForDelivery": {
        "type": "boolean"
      },
      "recordType": {
        "const": "chapter-delivery"
      },
      "schemaVersion": {
        "const": "dsh-novel.delivery.manifest.v2"
      },
      "stages": {
        "additionalProperties": {
          "additionalProperties": true,
          "properties": {
            "chapterId": {
              "pattern": "^ch_\\d+$",
              "type": "string"
            },
            "evidence": {
              "type": "object"
            },
            "recordType": {
              "const": "delivery-stage"
            },
            "schemaVersion": {
              "const": "dsh-novel.delivery.stage.v2"
            },
            "stage": {
              "minLength": 1,
              "type": "string"
            },
            "status": {
              "minLength": 1,
              "type": "string"
            },
            "verdict": {
              "enum": [
                "pass",
                "fail",
                "inconclusive"
              ]
            }
          },
          "required": [
            "schemaVersion",
            "recordType",
            "chapterId",
            "stage",
            "verdict",
            "status",
            "evidence"
          ],
          "type": "object"
        },
        "minProperties": 1,
        "type": "object"
      },
      "threshold": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "stages"
    ],
    "title": "dsh-novel delivery manifest v2",
    "type": "object"
  },
  "delivery_stage_v2": {
    "$id": "https://openwrite.dev/schemas/delivery-stage-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "evidence": {
        "type": "object"
      },
      "recordType": {
        "const": "delivery-stage"
      },
      "schemaVersion": {
        "const": "dsh-novel.delivery.stage.v2"
      },
      "stage": {
        "minLength": 1,
        "type": "string"
      },
      "status": {
        "minLength": 1,
        "type": "string"
      },
      "verdict": {
        "enum": [
          "pass",
          "fail",
          "inconclusive"
        ]
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "stage",
      "verdict",
      "status",
      "evidence"
    ],
    "title": "dsh-novel delivery stage v2",
    "type": "object"
  },
  "model_benchmark_v1": {
    "$id": "https://openwrite.dev/schemas/model-benchmark-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "candidates": {
        "items": {
          "additionalProperties": true,
          "disallowed": [
            "api_key",
            "embedding_api_key",
            "secret"
          ],
          "properties": {
            "candidate_id": {
              "minLength": 1,
              "type": "string"
            },
            "cost_reported": {
              "type": "boolean"
            },
            "cost_usd": {
              "type": [
                "number",
                "null"
              ]
            },
            "error": {
              "additionalProperties": true,
              "properties": {
                "code": {
                  "minLength": 1,
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "message"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "latency_ms": {
              "type": [
                "integer",
                "null"
              ]
            },
            "reliability_status": {
              "enum": [
                "completed",
                "failed"
              ]
            },
            "usage": {
              "additionalProperties": true,
              "properties": {
                "completion_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "prompt_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "reasoning_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "total_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                }
              },
              "type": [
                "object",
                "null"
              ]
            },
            "writer_profile": {
              "type": "object"
            }
          },
          "required": [
            "candidate_id",
            "writer_profile",
            "reliability_status"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "config": {
        "additionalProperties": true,
        "properties": {
          "blind_review": {
            "type": "boolean"
          },
          "concurrency": {
            "maximum": 4,
            "minimum": 1,
            "type": "integer"
          },
          "execution_mode": {
            "enum": [
              "framework",
              "creative"
            ]
          },
          "repeats": {
            "maximum": 5,
            "minimum": 1,
            "type": "integer"
          },
          "reviewer_profile_ids": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "run_scoped_profiles": {
            "type": "boolean"
          },
          "target_words": {
            "maximum": 12000,
            "minimum": 200,
            "type": "integer"
          },
          "writer_profile_ids": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "writer_profile_ids",
          "reviewer_profile_ids"
        ],
        "type": "object"
      },
      "context_hash": {
        "minLength": 1,
        "type": "string"
      },
      "evaluations": {
        "items": {
          "additionalProperties": true,
          "disallowed": [
            "api_key",
            "embedding_api_key",
            "secret"
          ],
          "properties": {
            "candidate_id": {
              "minLength": 1,
              "type": "string"
            },
            "cost_reported": {
              "type": "boolean"
            },
            "cost_usd": {
              "type": [
                "number",
                "null"
              ]
            },
            "error": {
              "additionalProperties": true,
              "properties": {
                "code": {
                  "minLength": 1,
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "message"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "execution_status": {
              "enum": [
                "completed",
                "partial",
                "failed"
              ]
            },
            "latency_ms": {
              "type": [
                "integer",
                "null"
              ]
            },
            "reviewer_profile": {
              "type": "object"
            },
            "usage": {
              "additionalProperties": true,
              "properties": {
                "completion_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "prompt_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "reasoning_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "total_tokens": {
                  "type": [
                    "integer",
                    "null"
                  ]
                }
              },
              "type": [
                "object",
                "null"
              ]
            }
          },
          "required": [
            "candidate_id",
            "reviewer_profile",
            "execution_status"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "run_id": {
        "pattern": "^bench_[A-Za-z0-9_-]+$",
        "type": "string"
      },
      "schema_version": {
        "const": "openwrite.model-benchmark.v1"
      },
      "started_at": {
        "minLength": 1,
        "type": "string"
      },
      "status": {
        "enum": [
          "completed",
          "partial",
          "failed"
        ]
      },
      "summary": {
        "additionalProperties": true,
        "properties": {
          "failed_candidates": {
            "minimum": 0,
            "type": "integer"
          },
          "latency_ms_total": {
            "type": [
              "integer",
              "null"
            ]
          }
        },
        "type": "object"
      },
      "task_id": {
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "schema_version",
      "run_id",
      "status",
      "context_hash",
      "config",
      "candidates",
      "evaluations"
    ],
    "title": "OpenWrite model benchmark v1 artifact",
    "type": "object"
  },
  "model_connection_test_v1": {
    "$id": "https://openwrite.dev/schemas/model-connection-test-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "disallowed": [
      "api_key",
      "embedding_api_key",
      "secret",
      "credential"
    ],
    "properties": {
      "base_url": {
        "type": "string"
      },
      "dimension": {
        "minimum": 1,
        "type": "integer"
      },
      "latency_ms": {
        "minimum": 0,
        "type": "integer"
      },
      "max_tokens": {
        "minimum": 1,
        "type": "integer"
      },
      "model": {
        "minLength": 1,
        "type": "string"
      },
      "ok": {
        "const": true
      },
      "provider": {
        "minLength": 1,
        "type": "string"
      },
      "provider_label": {
        "type": "string"
      },
      "reply": {
        "type": "string"
      },
      "status": {
        "const": "ok"
      },
      "tested_at": {
        "minLength": 1,
        "type": "string"
      },
      "vectors": {
        "minimum": 1,
        "type": "integer"
      }
    },
    "required": [
      "ok",
      "status",
      "provider",
      "model",
      "latency_ms",
      "tested_at"
    ],
    "title": "OpenWrite model connection test v1 success payload (chat and embedding variants)",
    "type": "object"
  },
  "model_profile_surface_v1": {
    "$defs": {
      "chat_profile": {
        "additionalProperties": true,
        "disallowed": [
          "api_key",
          "embedding_api_key",
          "secret"
        ],
        "properties": {
          "capabilities": {
            "properties": {
              "chat": {
                "const": true
              }
            },
            "required": [
              "chat"
            ],
            "type": "object"
          },
          "configured": {
            "type": "boolean"
          },
          "id": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "last_test": {
            "$ref": "#/$defs/test"
          },
          "model": {
            "type": "string"
          },
          "provider": {
            "type": "string"
          },
          "schema_version": {
            "const": "openwrite.model-profile.v1"
          },
          "used_by_routes": {
            "items": {
              "enum": [
                "goethe",
                "dante",
                "chapter_write",
                "review",
                "source_extract",
                "revision",
                "search",
                "research"
              ]
            },
            "type": "array"
          }
        },
        "required": [
          "id",
          "label",
          "provider",
          "model",
          "configured",
          "schema_version",
          "capabilities",
          "used_by_routes",
          "last_test"
        ],
        "type": "object"
      },
      "embedding_profile": {
        "additionalProperties": true,
        "disallowed": [
          "api_key",
          "embedding_api_key",
          "secret"
        ],
        "properties": {
          "active": {
            "type": "boolean"
          },
          "base_url": {
            "type": "string"
          },
          "configured": {
            "type": "boolean"
          },
          "dimension": {
            "minimum": 1,
            "type": "integer"
          },
          "id": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "last_test": {
            "$ref": "#/$defs/test"
          },
          "max_tokens": {
            "minimum": 1,
            "type": "integer"
          },
          "model": {
            "type": "string"
          },
          "provider": {
            "type": "string"
          },
          "schema_version": {
            "const": "openwrite.embedding-profile.v1"
          }
        },
        "required": [
          "id",
          "label",
          "provider",
          "model",
          "dimension",
          "max_tokens",
          "configured",
          "active",
          "schema_version",
          "last_test"
        ],
        "type": "object"
      },
      "test": {
        "additionalProperties": true,
        "disallowed": [
          "api_key",
          "secret",
          "credential"
        ],
        "properties": {
          "error_code": {
            "type": [
              "string",
              "null"
            ]
          },
          "failed_stage": {
            "type": "null"
          },
          "latency_ms": {
            "minimum": 0,
            "type": "integer"
          },
          "provider": {
            "type": "string"
          },
          "resolved_model": {
            "type": "string"
          },
          "status": {
            "enum": [
              "ok",
              "failed"
            ]
          },
          "tested_at": {
            "type": "string"
          }
        },
        "required": [
          "status",
          "tested_at",
          "latency_ms",
          "provider",
          "resolved_model",
          "error_code",
          "failed_stage"
        ],
        "type": [
          "object",
          "null"
        ]
      }
    },
    "$id": "https://openwrite.dev/schemas/model-profile-surface-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "active_embedding_profile_id": {
        "type": "string"
      },
      "default_profile_id": {
        "minLength": 1,
        "type": "string"
      },
      "embedding_profiles": {
        "items": {
          "$ref": "#/$defs/embedding_profile"
        },
        "type": "array"
      },
      "profiles": {
        "items": {
          "$ref": "#/$defs/chat_profile"
        },
        "type": "array"
      },
      "routes": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "schema_version": {
        "const": "openwrite.model-profile.v1"
      }
    },
    "required": [
      "schema_version",
      "profiles",
      "routes",
      "default_profile_id",
      "embedding_profiles",
      "active_embedding_profile_id"
    ],
    "title": "OpenWrite independent chat and embedding model surface v1",
    "type": "object"
  },
  "research_surface_v1": {
    "$id": "https://openwrite.dev/schemas/research-surface-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "disallowed": [
      "api_key",
      "credential",
      "secret"
    ],
    "properties": {
      "available": {
        "type": "boolean"
      },
      "dependencies_ready": {
        "type": "boolean"
      },
      "model_route": {
        "additionalProperties": true,
        "disallowed": [
          "api_key",
          "credential",
          "secret"
        ],
        "properties": {
          "compatible": {
            "type": "boolean"
          },
          "configured": {
            "type": "boolean"
          },
          "label": {
            "type": "string"
          },
          "model": {
            "type": "string"
          },
          "profile_id": {
            "type": "string"
          },
          "provider": {
            "type": "string"
          }
        },
        "required": [
          "profile_id",
          "label",
          "model",
          "provider",
          "configured",
          "compatible"
        ],
        "type": "object"
      },
      "node_ready": {
        "type": "boolean"
      },
      "package_ready": {
        "type": "boolean"
      },
      "pnpm_ready": {
        "type": "boolean"
      },
      "reports": {
        "items": {
          "additionalProperties": true,
          "disallowed": [
            "api_key",
            "credential",
            "secret"
          ],
          "properties": {
            "bytes": {
              "minimum": 0,
              "type": "integer"
            },
            "completed_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "cost_usd": {
              "additionalProperties": true,
              "properties": {
                "reported": {
                  "type": "boolean"
                },
                "value": {
                  "minimum": 0,
                  "type": [
                    "number",
                    "null"
                  ]
                }
              },
              "required": [
                "value",
                "reported"
              ],
              "type": "object"
            },
            "created_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "episode_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "failure": {
              "additionalProperties": true,
              "disallowed": [
                "api_key",
                "credential",
                "secret"
              ],
              "properties": {
                "code": {
                  "minLength": 1,
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "message"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "id": {
              "minLength": 1,
              "type": "string"
            },
            "latency_ms": {
              "minimum": 0,
              "type": [
                "integer",
                "null"
              ]
            },
            "metrics": {
              "type": "object"
            },
            "model_profile": {
              "additionalProperties": true,
              "disallowed": [
                "api_key",
                "credential",
                "secret"
              ],
              "properties": {
                "id": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "label": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "model": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "provider": {
                  "type": [
                    "string",
                    "null"
                  ]
                }
              },
              "required": [
                "id",
                "label",
                "model",
                "provider"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "path": {
              "minLength": 1,
              "type": "string"
            },
            "search_provider": {
              "type": [
                "string",
                "null"
              ]
            },
            "source_count": {
              "minimum": 0,
              "type": [
                "integer",
                "null"
              ]
            },
            "sources": {
              "items": {
                "additionalProperties": true,
                "properties": {
                  "cited": {
                    "type": "boolean"
                  },
                  "source_type": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  }
                },
                "required": [
                  "title",
                  "url",
                  "source_type",
                  "cited"
                ],
                "type": "object"
              },
              "type": [
                "array",
                "null"
              ]
            },
            "sources_status": {
              "enum": [
                "ok",
                "unavailable"
              ]
            },
            "status": {
              "enum": [
                "succeeded",
                "failed",
                "needs_human_review",
                "unknown"
              ]
            },
            "task_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "title": {
              "type": "string"
            },
            "usage": {
              "additionalProperties": true,
              "properties": {
                "reported": {
                  "type": "boolean"
                },
                "total_tokens": {
                  "minimum": 0,
                  "type": [
                    "integer",
                    "null"
                  ]
                }
              },
              "required": [
                "total_tokens",
                "reported"
              ],
              "type": "object"
            },
            "word_count": {
              "minimum": 0,
              "type": [
                "integer",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "title",
            "status",
            "episode_id",
            "task_id",
            "created_at",
            "completed_at",
            "model_profile",
            "search_provider",
            "sources",
            "sources_status",
            "source_count",
            "word_count",
            "latency_ms",
            "usage",
            "cost_usd",
            "failure",
            "metrics",
            "path",
            "bytes"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "schema_version": {
        "const": "openwrite.research-surface.v1"
      },
      "settings": {
        "additionalProperties": true,
        "disallowed": [
          "api_key",
          "credential",
          "secret"
        ],
        "properties": {
          "search_provider": {
            "enum": [
              "bocha",
              "bing",
              "jina",
              "none"
            ]
          },
          "search_providers": {
            "items": {
              "additionalProperties": true,
              "disallowed": [
                "api_key",
                "credential",
                "secret"
              ],
              "properties": {
                "configured": {
                  "type": "boolean"
                },
                "credential_configured": {
                  "type": "boolean"
                },
                "id": {
                  "enum": [
                    "bocha",
                    "bing",
                    "jina",
                    "none"
                  ]
                },
                "label": {
                  "minLength": 1,
                  "type": "string"
                },
                "requires_api_key": {
                  "type": "boolean"
                }
              },
              "required": [
                "id",
                "label",
                "requires_api_key",
                "configured",
                "credential_configured"
              ],
              "type": "object"
            },
            "type": "array"
          }
        },
        "required": [
          "search_provider",
          "search_providers"
        ],
        "type": "object"
      },
      "setup_hint": {
        "type": "string"
      }
    },
    "required": [
      "schema_version",
      "available",
      "node_ready",
      "pnpm_ready",
      "package_ready",
      "dependencies_ready",
      "setup_hint",
      "settings",
      "reports",
      "model_route"
    ],
    "title": "OpenWrite research surface v1 (credential-free)",
    "type": "object"
  },
  "review_manifest_v2": {
    "$id": "https://openwrite.dev/schemas/review-manifest-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "coverage": {
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      },
      "decisionSource": {
        "enum": [
          "v2",
          "v1-adapter"
        ]
      },
      "qualityScore": {
        "maximum": 100,
        "minimum": 0,
        "type": [
          "number",
          "null"
        ]
      },
      "recordType": {
        "const": "review"
      },
      "schemaVersion": {
        "const": "dsh-novel.review.manifest.v2"
      },
      "threshold": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      },
      "verdict": {
        "enum": [
          "pass",
          "fail",
          "inconclusive"
        ]
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "verdict"
    ],
    "title": "dsh-novel review manifest v2",
    "type": "object"
  },
  "review_v2_decision": {
    "$id": "https://openwrite.dev/schemas/review-v2-decision.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "coverage": {
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      },
      "delivery_status": {
        "enum": [
          "pass",
          "revise",
          "blocked",
          "inconclusive",
          "stale"
        ]
      },
      "execution_status": {
        "enum": [
          "completed",
          "partial",
          "failed"
        ]
      },
      "gate_status": {
        "enum": [
          "pass",
          "blocked",
          "inconclusive"
        ]
      },
      "production_gate_status": {
        "enum": [
          "pass",
          "revise",
          "blocked",
          "inconclusive",
          "stale",
          "disabled",
          "disabled_uncalibrated"
        ]
      },
      "quality_score": {
        "maximum": 100,
        "minimum": 0,
        "type": [
          "number",
          "null"
        ]
      },
      "schema_version": {
        "const": "openwrite.review.v2"
      }
    },
    "required": [
      "schema_version",
      "execution_status",
      "quality_score",
      "coverage",
      "gate_status",
      "delivery_status",
      "production_gate_status"
    ],
    "title": "OpenWrite review v2 decision",
    "type": "object"
  },
  "task_surface_v1": {
    "$id": "https://openwrite.dev/schemas/task-surface-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "counts": {
        "type": "object"
      },
      "phase_order": {
        "items": {
          "enum": [
            "queued",
            "reading",
            "preparing",
            "model",
            "validating",
            "committing",
            "complete"
          ]
        },
        "type": "array"
      },
      "schema_version": {
        "const": "openwrite.task-surface.v1"
      },
      "tasks": {
        "items": {
          "additionalProperties": true,
          "disallowed": [
            "api_key",
            "credential",
            "secret"
          ],
          "properties": {
            "attempt": {
              "minimum": 1,
              "type": "integer"
            },
            "chapter_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "completed_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "created_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "error": {
              "additionalProperties": true,
              "properties": {
                "code": {
                  "minLength": 1,
                  "type": "string"
                },
                "failed_stage": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "message": {
                  "type": "string"
                },
                "recoverable": {
                  "type": "boolean"
                }
              },
              "required": [
                "code",
                "message",
                "recoverable"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "input_summary": {
              "type": [
                "string",
                "null"
              ]
            },
            "phase": {
              "enum": [
                "queued",
                "reading",
                "preparing",
                "model",
                "validating",
                "committing",
                "complete",
                null
              ]
            },
            "phase_index": {
              "type": [
                "integer",
                "null"
              ]
            },
            "progress": {
              "additionalProperties": true,
              "properties": {
                "completed_units": {
                  "minimum": 0,
                  "type": "integer"
                },
                "ratio": {
                  "maximum": 1,
                  "minimum": 0,
                  "type": [
                    "number",
                    "null"
                  ]
                },
                "total_units": {
                  "minimum": 0,
                  "type": "integer"
                },
                "unit_kind": {
                  "enum": [
                    "candidates",
                    "evaluations",
                    "chapters",
                    "files"
                  ]
                }
              },
              "required": [
                "completed_units",
                "total_units",
                "ratio",
                "unit_kind"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "result_ref": {
              "additionalProperties": true,
              "properties": {
                "id": {
                  "minLength": 1,
                  "type": "string"
                },
                "type": {
                  "enum": [
                    "chapter",
                    "review",
                    "revision",
                    "research_report",
                    "benchmark_run",
                    "import",
                    "archive"
                  ]
                }
              },
              "required": [
                "type",
                "id"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "retryable": {
              "type": "boolean"
            },
            "schema_version": {
              "minLength": 1,
              "type": "string"
            },
            "started_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "status": {
              "enum": [
                "pending",
                "running",
                "awaiting_confirmation",
                "completed",
                "failed",
                "cancelled",
                "interrupted"
              ]
            },
            "task_id": {
              "minLength": 1,
              "type": "string"
            },
            "type": {
              "minLength": 1,
              "type": "string"
            },
            "updated_at": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "task_id",
            "type",
            "status",
            "phase",
            "phase_index",
            "progress",
            "attempt",
            "retryable",
            "created_at",
            "updated_at",
            "started_at",
            "completed_at",
            "error",
            "result_ref",
            "input_summary",
            "chapter_id",
            "schema_version"
          ],
          "type": "object"
        },
        "type": "array"
      }
    },
    "required": [
      "schema_version",
      "phase_order",
      "tasks",
      "counts"
    ],
    "title": "OpenWrite task surface v1 (credential-free)",
    "type": "object"
  }
}

function validateContract(value: unknown, key: string, label: string): Record<string, unknown> {
  const errors = validateSchema(value, SCHEMAS[key] as SchemaMap)
  if (errors.length > 0) {
    throw new Error(`CONTRACT_INVALID: ${label} violates ${key}: ${errors.join('; ')}`)
  }
  return value as Record<string, unknown>
}

/** Validate `value` against the review_v2_decision schema; throw on failure. */
export function validateReviewV2Decision(value: unknown): ReviewV2Decision {
  return validateContract(value, 'review_v2_decision', 'review_v2') as ReviewV2Decision
}

/** Validate `value` against the review_manifest_v2 schema; throw on failure. */
export function validateReviewManifestV2(value: unknown): ReviewManifestV2 {
  return validateContract(value, 'review_manifest_v2', 'review manifest') as ReviewManifestV2
}

/** Validate `value` against the delivery_manifest_v2 schema; throw on failure. */
export function validateDeliveryManifestV2(value: unknown): DeliveryManifestV2 {
  return validateContract(value, 'delivery_manifest_v2', 'delivery manifest') as DeliveryManifestV2
}

/** Validate `value` against the delivery_stage_v2 schema; throw on failure. */
export function validateDeliveryStageV2(value: unknown): DeliveryStageV2 {
  return validateContract(value, 'delivery_stage_v2', 'delivery stage') as DeliveryStageV2
}

/** Validate `value` against the model_benchmark_v1 schema; throw on failure. */
export function validateModelBenchmarkV1(value: unknown): ModelBenchmarkV1 {
  return validateContract(value, 'model_benchmark_v1', 'benchmark') as ModelBenchmarkV1
}

/** Validate `value` against the model_profile_surface_v1 schema; throw on failure. */
export function validateModelProfileSurfaceV1(value: unknown): ModelProfileSurfaceV1 {
  return validateContract(value, 'model_profile_surface_v1', 'model profile surface') as ModelProfileSurfaceV1
}

/** Validate `value` against the task_surface_v1 schema; throw on failure. */
export function validateTaskSurfaceV1(value: unknown): TaskSurfaceV1 {
  return validateContract(value, 'task_surface_v1', 'task surface') as TaskSurfaceV1
}

/** Validate `value` against the research_surface_v1 schema; throw on failure. */
export function validateResearchSurfaceV1(value: unknown): ResearchSurfaceV1 {
  return validateContract(value, 'research_surface_v1', 'research surface') as ResearchSurfaceV1
}

/** Validate `value` against the model_connection_test_v1 schema; throw on failure. */
export function validateModelConnectionTestV1(value: unknown): ModelConnectionTestV1 {
  return validateContract(value, 'model_connection_test_v1', 'model connection test') as ModelConnectionTestV1
}
