// generated by tools/schema_codegen.py (OpenWrite), do not edit
// sources:
//   review-v2-decision.schema.json sha256:a7c5214a498a $id: https://openwrite.dev/schemas/review-v2-decision.schema.json
//   review-manifest-v2.schema.json sha256:c74873990a9d $id: https://openwrite.dev/schemas/review-manifest-v2.schema.json
//   delivery-manifest-v2.schema.json sha256:cb149eae6952 $id: https://openwrite.dev/schemas/delivery-manifest-v2.schema.json
//   delivery-stage-v2.schema.json sha256:04d2637e1e4d $id: https://openwrite.dev/schemas/delivery-stage-v2.schema.json
//   model-benchmark-v1.schema.json sha256:256610806cff $id: https://openwrite.dev/schemas/model-benchmark-v1.schema.json
//   model-profile-surface-v1.schema.json sha256:fab06df1a21c $id: https://openwrite.dev/schemas/model-profile-surface-v1.schema.json
/** OpenWrite review v2 decision. Extra keys are allowed (additionalProperties). */
export interface ReviewV2Decision {
  schema_version: "openwrite.review.v2"
  execution_status: "completed" | "partial" | "failed"
  quality_score: number | null
  coverage: number
  gate_status: "pass" | "blocked" | "inconclusive"
  delivery_status: "pass" | "revise" | "blocked" | "inconclusive" | "stale"
  production_gate_status: "pass" | "revise" | "blocked" | "inconclusive" | "stale" | "disabled" | "disabled_uncalibrated"
  [key: string]: unknown
}

/** dsh-novel review manifest v2. Extra keys are allowed (additionalProperties). */
export interface ReviewManifestV2 {
  schemaVersion: "dsh-novel.review.manifest.v2"
  recordType: "review"
  chapterId: string
  verdict: "pass" | "fail" | "inconclusive"
  decisionSource?: "v2" | "v1-adapter"
  threshold?: number
  coverage?: number
  qualityScore?: number | null
  [key: string]: unknown
}

/** DeliveryManifestV2Stage. Extra keys are allowed (additionalProperties). */
export interface DeliveryManifestV2Stage {
  schemaVersion: "dsh-novel.delivery.stage.v2"
  recordType: "delivery-stage"
  chapterId: string
  stage: string
  verdict: "pass" | "fail" | "inconclusive"
  status: string
  evidence: Record<string, unknown>
  [key: string]: unknown
}

/** dsh-novel delivery manifest v2. Extra keys are allowed (additionalProperties). */
export interface DeliveryManifestV2 {
  schemaVersion: "dsh-novel.delivery.manifest.v2"
  recordType: "chapter-delivery"
  chapterId: string
  novelId?: string
  threshold?: number
  decisionSource?: "v2" | "v1-adapter"
  readyForDelivery?: boolean
  stages: Record<string, DeliveryManifestV2Stage>
  [key: string]: unknown
}

/** dsh-novel delivery stage v2. Extra keys are allowed (additionalProperties). */
export interface DeliveryStageV2 {
  schemaVersion: "dsh-novel.delivery.stage.v2"
  recordType: "delivery-stage"
  chapterId: string
  stage: string
  verdict: "pass" | "fail" | "inconclusive"
  status: string
  evidence: Record<string, unknown>
  [key: string]: unknown
}

/** ModelBenchmarkV1Config. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1Config {
  writer_profile_ids: string[]
  reviewer_profile_ids: string[]
  repeats?: number
  target_words?: number
  concurrency?: number
  blind_review?: boolean
  run_scoped_profiles?: boolean
  execution_mode?: "framework" | "creative"
  [key: string]: unknown
}

/** OpenWrite model benchmark v1 artifact. Extra keys are allowed (additionalProperties). */
export interface ModelBenchmarkV1 {
  schema_version: "openwrite.model-benchmark.v1"
  run_id: string
  status: "completed" | "partial" | "failed"
  context_hash: string
  candidates: unknown[]
  evaluations: unknown[]
  config: ModelBenchmarkV1Config
  [key: string]: unknown
}

/** ModelProfileSurfaceV1Profile. Extra keys are allowed (additionalProperties). */
export interface ModelProfileSurfaceV1Profile {
  id: string
  label: string
  provider: string
  model: string
  configured: boolean
  embedding_configured?: boolean
  credential_updated_at?: string
  [key: string]: unknown
}

/** OpenWrite model profile surface v1 (credential-free). Extra keys are allowed (additionalProperties). */
export interface ModelProfileSurfaceV1 {
  schema_version: "openwrite.model-profile.v1"
  default_profile_id: string
  legacy_mapped?: boolean
  profiles: ModelProfileSurfaceV1Profile[]
  routes: Record<string, string>
  [key: string]: unknown
}

type SchemaMap = Record<string, unknown>

function typeOk(value: unknown, name: string): boolean {
  switch (name) {
    case 'object': return value !== null && typeof value === 'object' && !Array.isArray(value)
    case 'array': return Array.isArray(value)
    case 'null': return value === null
    case 'integer': return Number.isInteger(value)
    case 'number': return typeof value === 'number' && !Number.isNaN(value)
    default: return typeof value === name
  }
}

/** Minimal JSON Schema subset validator mirroring OpenWrite
 * `tools/schema_lint.py` and `scripts/schema-lint.mjs`. */
export function validateSchema(value: unknown, schema: SchemaMap, path = '$'): string[] {
  const errors: string[] = []
  const fail = (message: string) => errors.push(`${path}: ${message}`)

  const rawType = schema['type']
  if (rawType !== undefined) {
    const names = Array.isArray(rawType) ? rawType.map(String) : [String(rawType)]
    if (!names.some(name => typeOk(value, name))) {
      const got = value === null ? 'null' : Array.isArray(value) ? 'array' : typeof value
      fail(`expected type ${names.join('/')}, got ${got}`)
      return errors
    }
  }

  if (schema['const'] !== undefined && value !== schema['const']) {
    fail(`expected const ${JSON.stringify(schema['const'])}, got ${JSON.stringify(value)}`)
  }

  const enumValues = schema['enum']
  if (Array.isArray(enumValues) && !enumValues.includes(value)) {
    fail(`${JSON.stringify(value)} not in enum ${JSON.stringify(enumValues)}`)
  }

  if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
    const record = value as Record<string, unknown>
    for (const key of (schema['required'] as string[] | undefined) ?? []) {
      if (!(key in record)) fail(`missing required property '${key}'`)
    }
    for (const key of (schema['disallowed'] as string[] | undefined) ?? []) {
      if (key in record) fail(`forbidden credential-like property '${key}' must not appear`)
    }
    const properties = (schema['properties'] as Record<string, SchemaMap> | undefined) ?? {}
    const additional = schema['additionalProperties']
    for (const [key, sub] of Object.entries(record)) {
      if (key in properties) {
        errors.push(...validateSchema(sub, properties[key] as SchemaMap, `${path}.${key}`))
      } else if (additional === false) {
        fail(`unexpected property '${key}'`)
      } else if (additional !== undefined && typeof additional === 'object') {
        errors.push(...validateSchema(sub, additional as SchemaMap, `${path}.${key}`))
      }
    }
    const minProperties = schema['minProperties']
    if (typeof minProperties === 'number' && Object.keys(record).length < minProperties) {
      fail(`expected at least ${minProperties} properties, got ${Object.keys(record).length}`)
    }
  }

  const items = schema['items']
  if (Array.isArray(value) && items !== undefined && typeof items === 'object') {
    value.forEach((item, index) => {
      errors.push(...validateSchema(item, items as SchemaMap, `${path}[${index}]`))
    })
  }

  if (typeof value === 'number' && !Number.isNaN(value)) {
    const minimum = schema['minimum']
    if (typeof minimum === 'number' && value < minimum) {
      fail(`${value} is less than minimum ${minimum}`)
    }
    const maximum = schema['maximum']
    if (typeof maximum === 'number' && value > maximum) {
      fail(`${value} is greater than maximum ${maximum}`)
    }
  }

  if (typeof value === 'string') {
    const minLength = schema['minLength']
    if (typeof minLength === 'number' && value.length < minLength) {
      fail(`string shorter than minLength ${minLength}`)
    }
    const pattern = schema['pattern']
    if (typeof pattern === 'string' && new RegExp(pattern).test(value) === false) {
      fail(`'${value}' does not match pattern '${pattern}'`)
    }
  }

  return errors
}

const SCHEMAS: Record<string, SchemaMap> = {
  "delivery_manifest_v2": {
    "$id": "https://openwrite.dev/schemas/delivery-manifest-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "decisionSource": {
        "enum": [
          "v2",
          "v1-adapter"
        ]
      },
      "novelId": {
        "minLength": 1,
        "type": "string"
      },
      "readyForDelivery": {
        "type": "boolean"
      },
      "recordType": {
        "const": "chapter-delivery"
      },
      "schemaVersion": {
        "const": "dsh-novel.delivery.manifest.v2"
      },
      "stages": {
        "additionalProperties": {
          "additionalProperties": true,
          "properties": {
            "chapterId": {
              "pattern": "^ch_\\d+$",
              "type": "string"
            },
            "evidence": {
              "type": "object"
            },
            "recordType": {
              "const": "delivery-stage"
            },
            "schemaVersion": {
              "const": "dsh-novel.delivery.stage.v2"
            },
            "stage": {
              "minLength": 1,
              "type": "string"
            },
            "status": {
              "minLength": 1,
              "type": "string"
            },
            "verdict": {
              "enum": [
                "pass",
                "fail",
                "inconclusive"
              ]
            }
          },
          "required": [
            "schemaVersion",
            "recordType",
            "chapterId",
            "stage",
            "verdict",
            "status",
            "evidence"
          ],
          "type": "object"
        },
        "minProperties": 1,
        "type": "object"
      },
      "threshold": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "stages"
    ],
    "title": "dsh-novel delivery manifest v2",
    "type": "object"
  },
  "delivery_stage_v2": {
    "$id": "https://openwrite.dev/schemas/delivery-stage-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "evidence": {
        "type": "object"
      },
      "recordType": {
        "const": "delivery-stage"
      },
      "schemaVersion": {
        "const": "dsh-novel.delivery.stage.v2"
      },
      "stage": {
        "minLength": 1,
        "type": "string"
      },
      "status": {
        "minLength": 1,
        "type": "string"
      },
      "verdict": {
        "enum": [
          "pass",
          "fail",
          "inconclusive"
        ]
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "stage",
      "verdict",
      "status",
      "evidence"
    ],
    "title": "dsh-novel delivery stage v2",
    "type": "object"
  },
  "model_benchmark_v1": {
    "$id": "https://openwrite.dev/schemas/model-benchmark-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "candidates": {
        "type": "array"
      },
      "config": {
        "additionalProperties": true,
        "properties": {
          "blind_review": {
            "type": "boolean"
          },
          "concurrency": {
            "maximum": 4,
            "minimum": 1,
            "type": "integer"
          },
          "execution_mode": {
            "enum": [
              "framework",
              "creative"
            ]
          },
          "repeats": {
            "maximum": 5,
            "minimum": 1,
            "type": "integer"
          },
          "reviewer_profile_ids": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "run_scoped_profiles": {
            "type": "boolean"
          },
          "target_words": {
            "maximum": 12000,
            "minimum": 200,
            "type": "integer"
          },
          "writer_profile_ids": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "writer_profile_ids",
          "reviewer_profile_ids"
        ],
        "type": "object"
      },
      "context_hash": {
        "minLength": 1,
        "type": "string"
      },
      "evaluations": {
        "type": "array"
      },
      "run_id": {
        "pattern": "^bench_[A-Za-z0-9_-]+$",
        "type": "string"
      },
      "schema_version": {
        "const": "openwrite.model-benchmark.v1"
      },
      "status": {
        "enum": [
          "completed",
          "partial",
          "failed"
        ]
      }
    },
    "required": [
      "schema_version",
      "run_id",
      "status",
      "context_hash",
      "config",
      "candidates",
      "evaluations"
    ],
    "title": "OpenWrite model benchmark v1 artifact",
    "type": "object"
  },
  "model_profile_surface_v1": {
    "$id": "https://openwrite.dev/schemas/model-profile-surface-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "default_profile_id": {
        "minLength": 1,
        "type": "string"
      },
      "legacy_mapped": {
        "type": "boolean"
      },
      "profiles": {
        "items": {
          "additionalProperties": true,
          "disallowed": [
            "api_key",
            "embedding_api_key",
            "secret"
          ],
          "properties": {
            "configured": {
              "type": "boolean"
            },
            "credential_updated_at": {
              "type": "string"
            },
            "embedding_configured": {
              "type": "boolean"
            },
            "id": {
              "minLength": 1,
              "type": "string"
            },
            "label": {
              "minLength": 1,
              "type": "string"
            },
            "model": {
              "minLength": 1,
              "type": "string"
            },
            "provider": {
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "id",
            "label",
            "provider",
            "model",
            "configured"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "routes": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "schema_version": {
        "const": "openwrite.model-profile.v1"
      }
    },
    "required": [
      "schema_version",
      "profiles",
      "routes",
      "default_profile_id"
    ],
    "title": "OpenWrite model profile surface v1 (credential-free)",
    "type": "object"
  },
  "review_manifest_v2": {
    "$id": "https://openwrite.dev/schemas/review-manifest-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "coverage": {
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      },
      "decisionSource": {
        "enum": [
          "v2",
          "v1-adapter"
        ]
      },
      "qualityScore": {
        "maximum": 100,
        "minimum": 0,
        "type": [
          "number",
          "null"
        ]
      },
      "recordType": {
        "const": "review"
      },
      "schemaVersion": {
        "const": "dsh-novel.review.manifest.v2"
      },
      "threshold": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      },
      "verdict": {
        "enum": [
          "pass",
          "fail",
          "inconclusive"
        ]
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "verdict"
    ],
    "title": "dsh-novel review manifest v2",
    "type": "object"
  },
  "review_v2_decision": {
    "$id": "https://openwrite.dev/schemas/review-v2-decision.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "coverage": {
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      },
      "delivery_status": {
        "enum": [
          "pass",
          "revise",
          "blocked",
          "inconclusive",
          "stale"
        ]
      },
      "execution_status": {
        "enum": [
          "completed",
          "partial",
          "failed"
        ]
      },
      "gate_status": {
        "enum": [
          "pass",
          "blocked",
          "inconclusive"
        ]
      },
      "production_gate_status": {
        "enum": [
          "pass",
          "revise",
          "blocked",
          "inconclusive",
          "stale",
          "disabled",
          "disabled_uncalibrated"
        ]
      },
      "quality_score": {
        "maximum": 100,
        "minimum": 0,
        "type": [
          "number",
          "null"
        ]
      },
      "schema_version": {
        "const": "openwrite.review.v2"
      }
    },
    "required": [
      "schema_version",
      "execution_status",
      "quality_score",
      "coverage",
      "gate_status",
      "delivery_status",
      "production_gate_status"
    ],
    "title": "OpenWrite review v2 decision",
    "type": "object"
  }
}

function validateContract(value: unknown, key: string, label: string): Record<string, unknown> {
  const errors = validateSchema(value, SCHEMAS[key] as SchemaMap)
  if (errors.length > 0) {
    throw new Error(`CONTRACT_INVALID: ${label} violates ${key}: ${errors.join('; ')}`)
  }
  return value as Record<string, unknown>
}

/** Validate `value` against the review_v2_decision schema; throw on failure. */
export function validateReviewV2Decision(value: unknown): ReviewV2Decision {
  return validateContract(value, 'review_v2_decision', 'review_v2') as ReviewV2Decision
}

/** Validate `value` against the review_manifest_v2 schema; throw on failure. */
export function validateReviewManifestV2(value: unknown): ReviewManifestV2 {
  return validateContract(value, 'review_manifest_v2', 'review manifest') as ReviewManifestV2
}

/** Validate `value` against the delivery_manifest_v2 schema; throw on failure. */
export function validateDeliveryManifestV2(value: unknown): DeliveryManifestV2 {
  return validateContract(value, 'delivery_manifest_v2', 'delivery manifest') as DeliveryManifestV2
}

/** Validate `value` against the delivery_stage_v2 schema; throw on failure. */
export function validateDeliveryStageV2(value: unknown): DeliveryStageV2 {
  return validateContract(value, 'delivery_stage_v2', 'delivery stage') as DeliveryStageV2
}

/** Validate `value` against the model_benchmark_v1 schema; throw on failure. */
export function validateModelBenchmarkV1(value: unknown): ModelBenchmarkV1 {
  return validateContract(value, 'model_benchmark_v1', 'benchmark') as ModelBenchmarkV1
}

/** Validate `value` against the model_profile_surface_v1 schema; throw on failure. */
export function validateModelProfileSurfaceV1(value: unknown): ModelProfileSurfaceV1 {
  return validateContract(value, 'model_profile_surface_v1', 'model profile surface') as ModelProfileSurfaceV1
}
