import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  validateDeliveryManifestV2,
  validateDeliveryStageV2,
  validateModelBenchmarkV1,
  validateModelProfileSurfaceV1,
  validateReviewManifestV2,
  validateReviewV2Decision,
} from '../lib/contracts-generated.js'
import { validateOrRaise, validateSchema } from './schema-lint.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const openwriteRoot = process.env.OPENWRITE_ROOT ?? join(here, '..', '..', '..', '..', 'OpenWrite')
const fixturePath = join(openwriteRoot, 'tests', 'fixtures', 'contracts', 'canonical_v2.json')
const fixture = JSON.parse(await readFile(fixturePath, 'utf8'))

// ── load the shared machine-readable schemas (source of truth) ──────────────
const schemas = Object.fromEntries(await Promise.all([
  'review-v2-decision', 'review-manifest-v2', 'delivery-manifest-v2',
  'delivery-stage-v2', 'model-benchmark-v1', 'model-profile-surface-v1',
].map(async name => [
  name,
  JSON.parse(await readFile(join(openwriteRoot, 'contracts', `${name}.schema.json`), 'utf8')),
])))

const SCHEMA_BY_KEY = {
  review: 'review-v2-decision',
  delivery: 'delivery-manifest-v2',
  model_profile: 'model-profile-surface-v1',
  benchmark: 'model-benchmark-v1',
}
// Golden fixture must pass the shared schemas on the JS side, mirroring
// tests/test_contract_schema_parity.py on the Python side.
for (const [key, schemaName] of Object.entries(SCHEMA_BY_KEY)) {
  validateOrRaise(fixture[key], schemas[schemaName])
}

const review = fixture.review
assert.equal(review.schema_version, 'openwrite.review.v2')
for (const field of ['quality_score', 'coverage', 'gate_status', 'delivery_status', 'production_gate_status', 'execution_status']) {
  assert.ok(Object.hasOwn(review, field), `review field: ${field}`)
}
assert.equal(fixture.delivery.schemaVersion, 'dsh-novel.delivery.manifest.v2')
assert.equal(fixture.model_profile.schema_version, 'openwrite.model-profile.v1')
assert.equal(fixture.benchmark.schema_version, 'openwrite.model-benchmark.v1')
assert.equal(JSON.stringify(fixture).includes('api_key'), false)
assert.equal(JSON.stringify(fixture).includes('secret'), false)

// ── parity matrix: same verdicts as the Python tests ────────────────────────
// review v2: unknown/missing schema version and bad enums fail on both sides.
for (const mutate of [
  { schema_version: 'openwrite.review.v999' },
  { execution_status: 'finished' },
  { coverage: 1.5 },
  { quality_score: 120 },
]) {
  assert.ok(validateSchema({ ...review, ...mutate }, schemas['review-v2-decision']), JSON.stringify(mutate))
}
const reviewMissing = { ...review }
delete reviewMissing.schema_version
assert.ok(validateSchema(reviewMissing, schemas['review-v2-decision']))

// benchmark: bad status / array types fail on both sides.
for (const mutate of [
  { status: 'done' },
  { candidates: 'nope' },
  { evaluations: null },
]) {
  assert.ok(validateSchema({ ...fixture.benchmark, ...mutate }, schemas['model-benchmark-v1']), JSON.stringify(mutate))
}

// profile surface: credentials must never appear in a valid surface.
const leakedProfile = {
  ...fixture.model_profile,
  profiles: [{ ...fixture.model_profile.profiles[0], api_key: 'must-not-appear' }],
}
assert.ok(validateSchema(leakedProfile, schemas['model-profile-surface-v1']))

// delivery stage: bad verdict and empty status fail on both sides.
const stageSchema = schemas['delivery-manifest-v2'].properties.stages.additionalProperties
const stageBase = fixture.delivery.stages.writing
assert.equal(validateSchema(stageBase, stageSchema).length, 0)
assert.ok(validateSchema({ ...stageBase, verdict: 'excellent' }, stageSchema))
assert.ok(validateSchema({ ...stageBase, status: '' }, stageSchema))

// ── generated validators (schema-derived runtime path) ──────────────────────
// Mirrors tests/test_contract_schema_parity.py: the validators generated by
// OpenWrite tools/schema_codegen.py must agree with the shared schemas on the
// same matrix, throwing CONTRACT_INVALID errors.
const generatedByKey = {
  review: ['review-v2-decision', validateReviewV2Decision],
  delivery: ['delivery-manifest-v2', validateDeliveryManifestV2],
  model_profile: ['model-profile-surface-v1', validateModelProfileSurfaceV1],
  benchmark: ['model-benchmark-v1', validateModelBenchmarkV1],
}
for (const [key, [schemaName, validate]] of Object.entries(generatedByKey)) {
  assert.equal(validateSchema(fixture[key], schemas[schemaName]).length, 0, key)
  validate(fixture[key])
}

const generatedNegative = (label, key, mutate) => {
  const [schemaName, validate] = generatedByKey[key]
  const bad = structuredClone(fixture[key])
  for (const [field, value] of Object.entries(mutate)) {
    if (value === undefined) delete bad[field]
    else bad[field] = value
  }
  assert.ok(validateSchema(bad, schemas[schemaName]), label)
  assert.throws(() => validate(bad), /CONTRACT_INVALID/, label)
}

generatedNegative('review unknown version', 'review', { schema_version: 'openwrite.review.v999' })
generatedNegative('review bad execution enum', 'review', { execution_status: 'finished' })
generatedNegative('review bad gate enum', 'review', { gate_status: 'ok' })
generatedNegative('review bad delivery enum', 'review', { delivery_status: 'maybe' })
generatedNegative('review coverage above range', 'review', { coverage: 1.5 })
generatedNegative('review quality above range', 'review', { quality_score: 120 })
generatedNegative('review bool is not a number', 'review', { coverage: true })
generatedNegative('review missing schema_version', 'review', { schema_version: undefined })
generatedNegative('benchmark bad status', 'benchmark', { status: 'done' })
generatedNegative('benchmark candidates not array', 'benchmark', { candidates: 'nope' })
generatedNegative('benchmark evaluations null', 'benchmark', { evaluations: null })
generatedNegative('benchmark unknown version', 'benchmark', { schema_version: 'openwrite.model-benchmark.v9' })
generatedNegative('benchmark missing context_hash', 'benchmark', { context_hash: undefined })
generatedNegative('delivery unknown version', 'delivery', { schemaVersion: 'dsh-novel.delivery.manifest.v9' })
generatedNegative('delivery bad recordType', 'delivery', { recordType: 'delivery' })
generatedNegative('delivery missing stages', 'delivery', { stages: undefined })
generatedNegative('delivery empty stages', 'delivery', { stages: {} })

// Non-object roots: the shared schemas and the generated validators agree.
for (const bad of [[], null, 'text', 42, true]) {
  assert.ok(validateSchema(bad, schemas['review-v2-decision']), `root ${String(bad)}`)
  assert.throws(() => validateReviewV2Decision(bad), /CONTRACT_INVALID/)
}

// Nested and credential negatives.
const leakedGenerated = structuredClone(fixture.model_profile)
leakedGenerated.profiles[0].api_key = 'must-not-appear'
assert.throws(() => validateModelProfileSurfaceV1(leakedGenerated), /CONTRACT_INVALID/)
const badStageManifest = structuredClone(fixture.delivery)
badStageManifest.stages.writing.verdict = 'excellent'
assert.throws(() => validateDeliveryManifestV2(badStageManifest), /CONTRACT_INVALID/)

// Review manifest and delivery stage contracts.
const manifestBase = {
  schemaVersion: 'dsh-novel.review.manifest.v2', recordType: 'review',
  chapterId: 'ch_001', verdict: 'pass',
}
validateReviewManifestV2(manifestBase)
for (const mutate of [
  { schemaVersion: 'dsh-novel.review.manifest.v999' },
  { recordType: 'review-batch' },
  { chapterId: 'chapter-1' },
  { verdict: 'excellent' },
]) {
  assert.throws(() => validateReviewManifestV2({ ...manifestBase, ...mutate }), /CONTRACT_INVALID/, JSON.stringify(mutate))
}
for (const key of ['schemaVersion', 'recordType', 'chapterId', 'verdict']) {
  const missing = { ...manifestBase }
  delete missing[key]
  assert.throws(() => validateReviewManifestV2(missing), /CONTRACT_INVALID/, key)
}
validateDeliveryStageV2(stageBase)
for (const mutate of [{ verdict: 'excellent' }, { status: '' }, { schemaVersion: 'v9' }]) {
  assert.throws(() => validateDeliveryStageV2({ ...stageBase, ...mutate }), /CONTRACT_INVALID/, JSON.stringify(mutate))
}

console.log('canonical contract smoke ok:', fixturePath)
