# generated by tools/schema_codegen.py, do not edit
# sources:
#   review-v2-decision.schema.json sha256:a7c5214a498a $id: https://openwrite.dev/schemas/review-v2-decision.schema.json
#   review-manifest-v2.schema.json sha256:c74873990a9d $id: https://openwrite.dev/schemas/review-manifest-v2.schema.json
#   delivery-manifest-v2.schema.json sha256:cb149eae6952 $id: https://openwrite.dev/schemas/delivery-manifest-v2.schema.json
#   delivery-stage-v2.schema.json sha256:04d2637e1e4d $id: https://openwrite.dev/schemas/delivery-stage-v2.schema.json
#   model-benchmark-v1.schema.json sha256:256610806cff $id: https://openwrite.dev/schemas/model-benchmark-v1.schema.json
#   model-profile-surface-v1.schema.json sha256:fab06df1a21c $id: https://openwrite.dev/schemas/model-profile-surface-v1.schema.json

"""Schema-derived contract types and validators (see tools/schema_codegen.py).

Validation failures raise ValueError; the Studio boundary translates them
into StudioError(code="CONTRACT_INVALID").
"""

from __future__ import annotations

import json
from typing import Any, Literal, TypedDict, cast

from tools.schema_lint import validate_schema

SCHEMAS: dict[str, Any] = json.loads(r"""
{
  "delivery_manifest_v2": {
    "$id": "https://openwrite.dev/schemas/delivery-manifest-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "decisionSource": {
        "enum": [
          "v2",
          "v1-adapter"
        ]
      },
      "novelId": {
        "minLength": 1,
        "type": "string"
      },
      "readyForDelivery": {
        "type": "boolean"
      },
      "recordType": {
        "const": "chapter-delivery"
      },
      "schemaVersion": {
        "const": "dsh-novel.delivery.manifest.v2"
      },
      "stages": {
        "additionalProperties": {
          "additionalProperties": true,
          "properties": {
            "chapterId": {
              "pattern": "^ch_\\d+$",
              "type": "string"
            },
            "evidence": {
              "type": "object"
            },
            "recordType": {
              "const": "delivery-stage"
            },
            "schemaVersion": {
              "const": "dsh-novel.delivery.stage.v2"
            },
            "stage": {
              "minLength": 1,
              "type": "string"
            },
            "status": {
              "minLength": 1,
              "type": "string"
            },
            "verdict": {
              "enum": [
                "pass",
                "fail",
                "inconclusive"
              ]
            }
          },
          "required": [
            "schemaVersion",
            "recordType",
            "chapterId",
            "stage",
            "verdict",
            "status",
            "evidence"
          ],
          "type": "object"
        },
        "minProperties": 1,
        "type": "object"
      },
      "threshold": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "stages"
    ],
    "title": "dsh-novel delivery manifest v2",
    "type": "object"
  },
  "delivery_stage_v2": {
    "$id": "https://openwrite.dev/schemas/delivery-stage-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "evidence": {
        "type": "object"
      },
      "recordType": {
        "const": "delivery-stage"
      },
      "schemaVersion": {
        "const": "dsh-novel.delivery.stage.v2"
      },
      "stage": {
        "minLength": 1,
        "type": "string"
      },
      "status": {
        "minLength": 1,
        "type": "string"
      },
      "verdict": {
        "enum": [
          "pass",
          "fail",
          "inconclusive"
        ]
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "stage",
      "verdict",
      "status",
      "evidence"
    ],
    "title": "dsh-novel delivery stage v2",
    "type": "object"
  },
  "model_benchmark_v1": {
    "$id": "https://openwrite.dev/schemas/model-benchmark-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "candidates": {
        "type": "array"
      },
      "config": {
        "additionalProperties": true,
        "properties": {
          "blind_review": {
            "type": "boolean"
          },
          "concurrency": {
            "maximum": 4,
            "minimum": 1,
            "type": "integer"
          },
          "execution_mode": {
            "enum": [
              "framework",
              "creative"
            ]
          },
          "repeats": {
            "maximum": 5,
            "minimum": 1,
            "type": "integer"
          },
          "reviewer_profile_ids": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "run_scoped_profiles": {
            "type": "boolean"
          },
          "target_words": {
            "maximum": 12000,
            "minimum": 200,
            "type": "integer"
          },
          "writer_profile_ids": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "writer_profile_ids",
          "reviewer_profile_ids"
        ],
        "type": "object"
      },
      "context_hash": {
        "minLength": 1,
        "type": "string"
      },
      "evaluations": {
        "type": "array"
      },
      "run_id": {
        "pattern": "^bench_[A-Za-z0-9_-]+$",
        "type": "string"
      },
      "schema_version": {
        "const": "openwrite.model-benchmark.v1"
      },
      "status": {
        "enum": [
          "completed",
          "partial",
          "failed"
        ]
      }
    },
    "required": [
      "schema_version",
      "run_id",
      "status",
      "context_hash",
      "config",
      "candidates",
      "evaluations"
    ],
    "title": "OpenWrite model benchmark v1 artifact",
    "type": "object"
  },
  "model_profile_surface_v1": {
    "$id": "https://openwrite.dev/schemas/model-profile-surface-v1.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "default_profile_id": {
        "minLength": 1,
        "type": "string"
      },
      "legacy_mapped": {
        "type": "boolean"
      },
      "profiles": {
        "items": {
          "additionalProperties": true,
          "disallowed": [
            "api_key",
            "embedding_api_key",
            "secret"
          ],
          "properties": {
            "configured": {
              "type": "boolean"
            },
            "credential_updated_at": {
              "type": "string"
            },
            "embedding_configured": {
              "type": "boolean"
            },
            "id": {
              "minLength": 1,
              "type": "string"
            },
            "label": {
              "minLength": 1,
              "type": "string"
            },
            "model": {
              "minLength": 1,
              "type": "string"
            },
            "provider": {
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "id",
            "label",
            "provider",
            "model",
            "configured"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "routes": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "schema_version": {
        "const": "openwrite.model-profile.v1"
      }
    },
    "required": [
      "schema_version",
      "profiles",
      "routes",
      "default_profile_id"
    ],
    "title": "OpenWrite model profile surface v1 (credential-free)",
    "type": "object"
  },
  "review_manifest_v2": {
    "$id": "https://openwrite.dev/schemas/review-manifest-v2.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "chapterId": {
        "pattern": "^ch_\\d+$",
        "type": "string"
      },
      "coverage": {
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      },
      "decisionSource": {
        "enum": [
          "v2",
          "v1-adapter"
        ]
      },
      "qualityScore": {
        "maximum": 100,
        "minimum": 0,
        "type": [
          "number",
          "null"
        ]
      },
      "recordType": {
        "const": "review"
      },
      "schemaVersion": {
        "const": "dsh-novel.review.manifest.v2"
      },
      "threshold": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      },
      "verdict": {
        "enum": [
          "pass",
          "fail",
          "inconclusive"
        ]
      }
    },
    "required": [
      "schemaVersion",
      "recordType",
      "chapterId",
      "verdict"
    ],
    "title": "dsh-novel review manifest v2",
    "type": "object"
  },
  "review_v2_decision": {
    "$id": "https://openwrite.dev/schemas/review-v2-decision.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "properties": {
      "coverage": {
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      },
      "delivery_status": {
        "enum": [
          "pass",
          "revise",
          "blocked",
          "inconclusive",
          "stale"
        ]
      },
      "execution_status": {
        "enum": [
          "completed",
          "partial",
          "failed"
        ]
      },
      "gate_status": {
        "enum": [
          "pass",
          "blocked",
          "inconclusive"
        ]
      },
      "production_gate_status": {
        "enum": [
          "pass",
          "revise",
          "blocked",
          "inconclusive",
          "stale",
          "disabled",
          "disabled_uncalibrated"
        ]
      },
      "quality_score": {
        "maximum": 100,
        "minimum": 0,
        "type": [
          "number",
          "null"
        ]
      },
      "schema_version": {
        "const": "openwrite.review.v2"
      }
    },
    "required": [
      "schema_version",
      "execution_status",
      "quality_score",
      "coverage",
      "gate_status",
      "delivery_status",
      "production_gate_status"
    ],
    "title": "OpenWrite review v2 decision",
    "type": "object"
  }
}
""")


class _ReviewV2DecisionRequired(TypedDict):
    """Required keys of ReviewV2Decision."""

    schema_version: Literal["openwrite.review.v2"]
    execution_status: Literal["completed", "partial", "failed"]
    quality_score: float | None
    coverage: float
    gate_status: Literal["pass", "blocked", "inconclusive"]
    delivery_status: Literal["pass", "revise", "blocked", "inconclusive", "stale"]
    production_gate_status: Literal[
        "pass",
        "revise",
        "blocked",
        "inconclusive",
        "stale",
        "disabled",
        "disabled_uncalibrated",
    ]


class ReviewV2Decision(_ReviewV2DecisionRequired, total=False):
    """OpenWrite review v2 decision."""


class _ReviewManifestV2Required(TypedDict):
    """Required keys of ReviewManifestV2."""

    schemaVersion: Literal["dsh-novel.review.manifest.v2"]
    recordType: Literal["review"]
    chapterId: str
    verdict: Literal["pass", "fail", "inconclusive"]


class ReviewManifestV2(_ReviewManifestV2Required, total=False):
    """dsh-novel review manifest v2."""

    decisionSource: Literal["v2", "v1-adapter"]
    threshold: int
    coverage: float
    qualityScore: float | None


class _DeliveryManifestV2StageRequired(TypedDict):
    """Required keys of DeliveryManifestV2Stage."""

    schemaVersion: Literal["dsh-novel.delivery.stage.v2"]
    recordType: Literal["delivery-stage"]
    chapterId: str
    stage: str
    verdict: Literal["pass", "fail", "inconclusive"]
    status: str
    evidence: dict[str, Any]


class DeliveryManifestV2Stage(_DeliveryManifestV2StageRequired, total=False):
    """DeliveryManifestV2Stage."""


class _DeliveryManifestV2Required(TypedDict):
    """Required keys of DeliveryManifestV2."""

    schemaVersion: Literal["dsh-novel.delivery.manifest.v2"]
    recordType: Literal["chapter-delivery"]
    chapterId: str
    stages: dict[str, DeliveryManifestV2Stage]


class DeliveryManifestV2(_DeliveryManifestV2Required, total=False):
    """dsh-novel delivery manifest v2."""

    novelId: str
    threshold: int
    decisionSource: Literal["v2", "v1-adapter"]
    readyForDelivery: bool


class _DeliveryStageV2Required(TypedDict):
    """Required keys of DeliveryStageV2."""

    schemaVersion: Literal["dsh-novel.delivery.stage.v2"]
    recordType: Literal["delivery-stage"]
    chapterId: str
    stage: str
    verdict: Literal["pass", "fail", "inconclusive"]
    status: str
    evidence: dict[str, Any]


class DeliveryStageV2(_DeliveryStageV2Required, total=False):
    """dsh-novel delivery stage v2."""


class _ModelBenchmarkV1ConfigRequired(TypedDict):
    """Required keys of ModelBenchmarkV1Config."""

    writer_profile_ids: list[str]
    reviewer_profile_ids: list[str]


class ModelBenchmarkV1Config(_ModelBenchmarkV1ConfigRequired, total=False):
    """ModelBenchmarkV1Config."""

    repeats: int
    target_words: int
    concurrency: int
    blind_review: bool
    run_scoped_profiles: bool
    execution_mode: Literal["framework", "creative"]


class _ModelBenchmarkV1Required(TypedDict):
    """Required keys of ModelBenchmarkV1."""

    schema_version: Literal["openwrite.model-benchmark.v1"]
    run_id: str
    status: Literal["completed", "partial", "failed"]
    context_hash: str
    candidates: list[Any]
    evaluations: list[Any]
    config: ModelBenchmarkV1Config


class ModelBenchmarkV1(_ModelBenchmarkV1Required, total=False):
    """OpenWrite model benchmark v1 artifact."""


class _ModelProfileSurfaceV1ProfileRequired(TypedDict):
    """Required keys of ModelProfileSurfaceV1Profile."""

    id: str
    label: str
    provider: str
    model: str
    configured: bool


class ModelProfileSurfaceV1Profile(_ModelProfileSurfaceV1ProfileRequired, total=False):
    """ModelProfileSurfaceV1Profile."""

    embedding_configured: bool
    credential_updated_at: str


class _ModelProfileSurfaceV1Required(TypedDict):
    """Required keys of ModelProfileSurfaceV1."""

    schema_version: Literal["openwrite.model-profile.v1"]
    default_profile_id: str
    profiles: list[ModelProfileSurfaceV1Profile]
    routes: dict[str, str]


class ModelProfileSurfaceV1(_ModelProfileSurfaceV1Required, total=False):
    """OpenWrite model profile surface v1 (credential-free)."""

    legacy_mapped: bool


def _validate(value: Any, key: str, label: str) -> dict[str, Any]:
    errors = validate_schema(value, SCHEMAS[key])
    if errors:
        raise ValueError(f"{label} violates {key} contract: {'; '.join(errors)}")
    return dict(value)


def validate_review_v2(value: Any) -> ReviewV2Decision:
    """Validate against review-v2-decision.schema.json (schema-derived)."""
    result = _validate(value, "review_v2_decision", "review_v2")
    return cast(ReviewV2Decision, result)


def validate_review_manifest_v2(value: Any) -> ReviewManifestV2:
    """Validate against review-manifest-v2.schema.json (schema-derived)."""
    result = _validate(value, "review_manifest_v2", "review manifest")
    return cast(ReviewManifestV2, result)


def validate_delivery_v2(value: Any) -> DeliveryManifestV2:
    """Validate against delivery-manifest-v2.schema.json (schema-derived)."""
    result = _validate(value, "delivery_manifest_v2", "delivery manifest")
    return cast(DeliveryManifestV2, result)


def validate_delivery_stage_v2(value: Any) -> DeliveryStageV2:
    """Validate against delivery-stage-v2.schema.json (schema-derived)."""
    result = _validate(value, "delivery_stage_v2", "delivery stage")
    return cast(DeliveryStageV2, result)


def validate_benchmark_v1(value: Any) -> ModelBenchmarkV1:
    """Validate against model-benchmark-v1.schema.json (schema-derived)."""
    result = _validate(value, "model_benchmark_v1", "benchmark")
    return cast(ModelBenchmarkV1, result)


def validate_model_profile_surface(value: Any) -> ModelProfileSurfaceV1:
    """Validate against model-profile-surface-v1.schema.json (schema-derived)."""
    result = _validate(value, "model_profile_surface_v1", "model profile surface")
    return cast(ModelProfileSurfaceV1, result)
