"""Librarian agent for chapter draft generation."""

from dataclasses import dataclass
from typing import Dict, List


@dataclass
class LibrarianOutput:
    """Story output generated by Librarian."""

    chapter_id: str
    beat_list: List[str]
    draft: str


class LibrarianAgent:
    """Generates chapter beats and a draft from constrained context."""

    def generate_beats(self, chapter_id: str, context: Dict[str, str]) -> List[str]:
        seed = context.get("seed", "推进主线并保留悬念")
        return [
            f"{chapter_id} 开场：建立当下冲突与目标",
            f"{chapter_id} 中段：推进人物决策并触发代价",
            f"{chapter_id} 结尾：制造新悬念，衔接下一章（{seed}）",
        ]

    def generate_chapter(
        self, chapter_id: str, objective: str, context: Dict[str, str]
    ) -> LibrarianOutput:
        beats = self.generate_beats(chapter_id, context)
        character_brief = context.get("characters", "暂无人物状态")
        outline_brief = context.get("outline", "暂无章节大纲")
        foreshadowing_brief = context.get("foreshadowing", "暂无待回收伏笔")

        lines: List[str] = [
            f"# {chapter_id} 章节草稿",
            "",
            "## 写作目标",
            objective,
            "",
            "## 上下文摘要",
            f"- 章节提要: {outline_brief}",
            f"- 人物状态: {character_brief}",
            f"- 待回收伏笔: {foreshadowing_brief}",
            "",
            "## 剧情节拍",
        ]
        lines.extend([f"{idx}. {beat}" for idx, beat in enumerate(beats, start=1)])
        lines.extend(
            [
                "",
                "## 草稿正文（模拟）",
                "夜色压低了街巷的声响，主角在旧城门前停住了脚步。",
                "他知道自己没有退路，只能把手里的线索继续追下去。",
                "当对手出现时，冲突被迫提前爆发，而代价也随之显现。",
                "这一章结束时，他得到答案的一角，但问题反而更多。",
            ]
        )

        return LibrarianOutput(chapter_id=chapter_id, beat_list=beats, draft="\n".join(lines) + "\n")
