"""Librarian agent for chapter draft generation and rewrite."""

from dataclasses import dataclass
from typing import Dict, List


@dataclass
class LibrarianOutput:
    """Story output generated by Librarian."""

    chapter_id: str
    beat_list: List[str]
    draft: str


class LibrarianAgent:
    """Generates chapter beats and a draft from constrained context."""

    def generate_beats(self, chapter_id: str, context: Dict[str, str]) -> List[str]:
        seed = context.get("seed", "推进主线并保留悬念")
        return [
            f"{chapter_id} 开场：建立当下冲突与目标",
            f"{chapter_id} 中段：推进人物决策并触发代价",
            f"{chapter_id} 结尾：制造新悬念，衔接下一章（{seed}）",
        ]

    def generate_chapter(
        self, chapter_id: str, objective: str, context: Dict[str, str]
    ) -> LibrarianOutput:
        beats = self.generate_beats(chapter_id, context)
        character_brief = context.get("characters", "暂无人物状态")
        outline_brief = context.get("outline", "暂无章节大纲")
        foreshadowing_brief = context.get("foreshadowing", "暂无待回收伏笔")

        lines: List[str] = [
            f"# {chapter_id} 章节草稿",
            "",
            "## 写作目标",
            objective,
            "",
            "## 上下文摘要",
            f"- 章节提要: {outline_brief}",
            f"- 人物状态: {character_brief}",
            f"- 待回收伏笔: {foreshadowing_brief}",
            "",
            "## 剧情节拍",
        ]
        lines.extend([f"{idx}. {beat}" for idx, beat in enumerate(beats, start=1)])
        lines.extend(
            [
                "",
                "## 草稿正文（模拟）",
                "夜色压低了街巷的声响，主角在旧城门前停住了脚步。",
                "他知道自己没有退路，只能把手里的线索继续追下去。",
                "当对手出现时，冲突被迫提前爆发，而代价也随之显现。",
                "这一章结束时，他得到答案的一角，但问题反而更多。",
            ]
        )

        return LibrarianOutput(chapter_id=chapter_id, beat_list=beats, draft="\n".join(lines) + "\n")

    def rewrite_chapter(
        self,
        *,
        chapter_id: str,
        objective: str,
        context: Dict[str, str],
        previous_draft: str,
        forbidden: List[str],
        required: List[str],
        errors: List[str],
        warnings: List[str],
        attempt: int,
    ) -> LibrarianOutput:
        """Apply lightweight rule-oriented rewrite based on checker feedback."""
        text = previous_draft

        for token in forbidden:
            if token:
                text = text.replace(token, "[已规避词]")

        missing_required = [token for token in required if token and token not in text]
        if missing_required:
            text += "\n\n## 规则补写\n"
            for token in missing_required:
                text += f"- 已补写要素：{token}\n"
                text += f"{token}在局势中被明确提及并推动决策。\n"

        feedback = (errors + warnings)[:3]
        if feedback:
            sanitized_feedback: List[str] = []
            for item in feedback:
                text_item = item
                for token in forbidden:
                    if token:
                        text_item = text_item.replace(token, "[已规避词]")
                sanitized_feedback.append(text_item)
            text += "\n\n> 修订记录\n"
            text += f"> 第{attempt}轮：根据 LoreChecker 反馈修订：{'；'.join(sanitized_feedback)}\n"

        beats = self.generate_beats(chapter_id, context)
        return LibrarianOutput(chapter_id=chapter_id, beat_list=beats, draft=text)
